
package com.hcl.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "calculator", targetNamespace = "http://soap.service.hcl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param n1
     * @param n2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "sum", targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.SumResponse")
    @Action(input = "http://soap.service.hcl.com/calculator/sumRequest", output = "http://soap.service.hcl.com/calculator/sumResponse")
    public int sum(
        @WebParam(name = "n1", targetNamespace = "")
        int n1,
        @WebParam(name = "n2", targetNamespace = "")
        int n2);

    /**
     * 
     * @param n1
     * @param n2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "res", targetNamespace = "")
    @RequestWrapper(localName = "res", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.Res")
    @ResponseWrapper(localName = "resResponse", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.ResResponse")
    @Action(input = "http://soap.service.hcl.com/calculator/resRequest", output = "http://soap.service.hcl.com/calculator/resResponse")
    public int res(
        @WebParam(name = "n1", targetNamespace = "")
        int n1,
        @WebParam(name = "n2", targetNamespace = "")
        int n2);

    /**
     * 
     * @param n1
     * @param n2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "mul", targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.MulResponse")
    @Action(input = "http://soap.service.hcl.com/calculator/mulRequest", output = "http://soap.service.hcl.com/calculator/mulResponse")
    public int mul(
        @WebParam(name = "n1", targetNamespace = "")
        int n1,
        @WebParam(name = "n2", targetNamespace = "")
        int n2);

    /**
     * 
     * @param n1
     * @param n2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "div", targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.DivResponse")
    @Action(input = "http://soap.service.hcl.com/calculator/divRequest", output = "http://soap.service.hcl.com/calculator/divResponse")
    public int div(
        @WebParam(name = "n1", targetNamespace = "")
        int n1,
        @WebParam(name = "n2", targetNamespace = "")
        int n2);

    /**
     * 
     * @param n1
     * @param n2
     * @param aux
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "fibo", targetNamespace = "")
    @RequestWrapper(localName = "fibo", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.Fibo")
    @ResponseWrapper(localName = "fiboResponse", targetNamespace = "http://soap.service.hcl.com/", className = "com.hcl.service.soap.FiboResponse")
    @Action(input = "http://soap.service.hcl.com/calculator/fiboRequest", output = "http://soap.service.hcl.com/calculator/fiboResponse")
    public int fibo(
        @WebParam(name = "n1", targetNamespace = "")
        int n1,
        @WebParam(name = "n2", targetNamespace = "")
        int n2,
        @WebParam(name = "aux", targetNamespace = "")
        int aux);

}
